/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Trabalho.view;

import Trabalho.model.Despesa;
import Trabalho.model.Lancamento;
import Trabalho.model.LancamentoController;
import Trabalho.model.Receita;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import java.time.LocalDate;

/**
 *
 * @author Usuario
 */
public class ItemLancamento extends javax.swing.JPanel {

    private Color hoverColor;
    private boolean selected;
    private LancamentoController controller;
    
    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }
    
    /**
     * Creates new form ItemLancamentoLista
     */
    public ItemLancamento(Lancamento lancamento, LancamentoController controller) {
        initComponents();
        this.controller = controller;
        
        setItem(lancamento);
        hoverColor = new Color(240,240,240);
        
        jPanel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseExited(MouseEvent e) {
                jPanel1.setBackground(new Color(255,255,255));
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                jPanel1.setBackground(hoverColor);
            }
            
        });
        
    }
    
    public void setItem(Object obj){
        if(obj instanceof Receita){
            Receita item = (Receita) obj;
            lbValor.setForeground(new Color(52, 193, 83));
            
            lbValor.setText(NumberFormat.getCurrencyInstance().format(item.getValor()));
            lbData.setText(item.getData().getDayOfMonth() + "/" + item.getData().getMonthValue() + "/" + item.getData().getYear());
            lbCategoria.setText(item.getCategoria().getNome());
            
            double saldoAnterior = controller.calcularSaldo(LocalDate.MIN, item.getData().minusDays(1));
            double saldoAtual = controller.calcularSaldo(LocalDate.MIN, item.getData());
            
            lbSaldo.setText(NumberFormat.getCurrencyInstance().format(saldoAnterior) + " -> " + NumberFormat.getCurrencyInstance().format(saldoAtual));
            
        }else if(obj instanceof Despesa){
            Despesa item = (Despesa) obj;
            lbValor.setForeground(new Color(243, 45, 45));
            
            lbValor.setText(NumberFormat.getCurrencyInstance().format(item.getValor()));
            lbData.setText(item.getData().getDayOfMonth() + "/" + item.getData().getMonthValue() + "/" + item.getData().getYear());
            lbCategoria.setText(item.getCategoria().getNome());
            
            double saldoAnterior = controller.calcularSaldo(LocalDate.MIN, item.getData().minusDays(1));
            double saldoAtual = controller.calcularSaldo(LocalDate.MIN, item.getData());
            
            lbSaldo.setText(NumberFormat.getCurrencyInstance().format(saldoAnterior) + " -> " + NumberFormat.getCurrencyInstance().format(saldoAtual));
            
        }else{
            lbValor.setText("null");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbValor = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        lbSaldo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(32767, 73));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lbValor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbValor.setText("VALOR");

        lbData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbData.setText("DD/MM/AAAA");

        lbCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbCategoria.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbCategoria.setText("Categoria");

        lbSaldo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbSaldo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbSaldo.setText("saldo: antes -> depois");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbValor)
                        .addGap(62, 62, 62)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(lbCategoria))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbSaldo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbValor)
                        .addComponent(jButton1))
                    .addComponent(lbCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbData)
                    .addComponent(lbSaldo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("Teste");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        
    }//GEN-LAST:event_formMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbSaldo;
    private javax.swing.JLabel lbValor;
    // End of variables declaration//GEN-END:variables

    public Color getHoverColor() {
        return hoverColor;
    }

    public void setHoverColor(Color hoverColor) {
        this.hoverColor = hoverColor;
    }

    
}
